### ISSUE TITLE
Can't change connected account

### ISSUE THREAD

**Issue by zzuziak** [snapshot-labs/sx-ui#741]
UI keeps connecting me to the same wallet

- Two wallet extensions (CB and MM)
- Connected with CB, want to log out and log in with MM
- Connect Wallet -> MM -> Connects with CB again

https://www.loom.com/share/bd61a27daccf4a8f87189eb907e1ac6f

**Comment by Sekhmet** [comment]
I think it's how Coinbase wallet hijacks Metamask's object to prioritise itself over MM.

The same can be reproduced on Snapshot.org, I think it's not intended to be doing what it does now (I think it should only hijack entirely if you confirm this), but if you sign in in certain order it will end up hijacking Metamask entirely (here or on Snapshot.org).

<img width="377" alt="image" src="https://github.com/snapshot-labs/sx-ui/assets/1968722/966c8140-3817-4bf5-b1fb-66370f81a157">

For example right now I can do this on Snapshot.org as well:
Refresh page -> sign in with Coinbase -> logout -> sign in with Metamask -> confirm I want to use Metamask -> it signs me in with Coinbase instead.

**Comment by samuveth** [comment]
@Sekhmet we fixed this on Snapshot like this https://github.com/snapshot-labs/snapshot/blob/ec4b865bfbe9cac6a5e16c1f2a96db685579a2a7/src/composables/useApp.ts#L42

**Comment by Sekhmet** [comment]
@samuveth it seems it doesn't solve this issue entirely? because I can reproduce it on Snapshot.org still (as described [there](https://github.com/snapshot-labs/sx-ui/issues/741#issuecomment-1731167538)).
